module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      spacing: {
        'golden-main': '61.8%',
        'golden-rest': '38.3%',
      },
      transform: ['hover'],
      // Generated by Animista
      // Licensed under FreeBSD License.
      // See http://animista.net/license for more info.
      // w: http://animista.net, t: @cssanimista
      animation: {
        'jello-horizontal': 'jello-horizontal 1s ease',
      },
      keyframes: {
        'jello-horizontal': {
          '0%,to': {
            transform: 'scale3d(1, 1, 1)',
          },
          '30%': {
            transform: 'scale3d(1.25, .75, 1)',
          },
          '40%': {
            transform: 'scale3d(.75, 1.25, 1)',
          },
          '50%': {
            transform: 'scale3d(1.15, .85, 1)',
          },
          '65%': {
            transform: 'scale3d(.95, 1.05, 1)',
          },
          '75%': {
            transform: 'scale3d(1.05, .95, 1)',
          },
        },
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
